AllCops:
  Include:
    - 'app/**/*'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'examples/**/*'
    - 'app/movies.txt'
    - 'Gemfile'
    -
AllCops:
  Exclude:
    - config/initializers/secret_token.rb

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
